apiVersion: v1
kind: Service
metadata:
    name: "testkubernetes-402b"
    labels:
        app: "testkubernetes-402b"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "testkubernetes-402b"